## Data Preprocessing / Data Preparation

1. Data Cleaning - drop, fillna with mean, median, mode imputation, changing data type
2. Data Transformation
   
       a. If data is CONTINUOUS = Standard Scalar, MinMaxScaler, Robust Scalar
       b. If data is DISCRETE = Label Encoder, One Hot Encoder

## 1. Import Necessary Libraries

In [2]:
import pandas as pd

## 2. Data Collection

In [3]:
weather_data = pd.read_csv("environmental_data.csv")
weather_data

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5    NaN      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

## 3. Data Understanding

### 3.1. Perform Initial Analysis of the data

In [6]:
weather_data.shape    #to get number of observations and features

(158, 10)

In [7]:
weather_data.isna().sum()     #to find the null entries of features

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

In [8]:
weather_data.dtypes      #to fetch the data type of each feature present in the dataset

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C         object
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

In [9]:
weather_data.describe(include='all')     #to display character column as well

,Unnamed: 0,Ozone,Solar.R,Wind,Temp C,Month,Day,Year,Temp,Weather
count,158.000000,120.000000,151.000000,158.000000,158,158,158.000000,158.0,158.000000,155
unique,NaN,NaN,NaN,NaN,41,6,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,81,9,NaN,NaN,NaN,S
freq,NaN,NaN,NaN,NaN,11,34,NaN,NaN,NaN,59
mean,79.500000,41.583333,185.403974,9.957595,NaN,NaN,16.006329,2010.0,77.727848,NaN
std,45.754781,32.620709,88.723103,3.511261,NaN,NaN,8.997166,0.0,9.377877,NaN
min,1.000000,1.000000,7.000000,1.700000,NaN,NaN,1.000000,2010.0,56.000000,NaN
25%,40.250000,18.000000,119.000000,7.400000,NaN,NaN,8.000000,2010.0,72.000000,NaN
50%,79.500000,30.500000,197.000000,9.700000,NaN,NaN,16.000000,2010.0,78.500000,NaN
75%,118.750000,61.500000,257.000000,11.875000,NaN,NaN,24.000000,2010.0,84.000000,NaN
max,158.000000,168.000000,334.000000,20.700000,NaN,NaN,31.000000,2010.0,97.000000,NaN

In [10]:
#find unique values on Weather feature

weather_data["Weather"].unique()

array(['S', 'C', 'PS', nan], dtype=object)

In [13]:
#find number of occurrences of Weather feature including null value count

weather_data["Weather"].value_counts(dropna=False)

Weather
S      59
C      49
PS     47
NaN     3
Name: count, dtype: int64

## 4. Data Preparation

#### 4.1 Data Cleaning - drop, fillna with Mean, Median, Mode Imputation, Changing Data Types

In [14]:
weather_data.head()

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S

In [15]:
#drop unnecessary columns like Unnamed. Drop Temp C as Temp column is already available
weather_data.drop(labels=["Unnamed: 0", "Temp C"], axis=1, inplace=True)

In [16]:
weather_data

     Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0     41.0    190.0   7.4     5    1  2010    67       S
1     36.0    118.0   8.0     5    2  2010    72       C
2     12.0    149.0  12.6     5    3  2010    74      PS
3     18.0    313.0  11.5     5    4  2010    62       S
4      NaN      NaN  14.3     5    5  2010    56       S
..     ...      ...   ...   ...  ...   ...   ...     ...
153   41.0    190.0   7.4     5    1  2010    67       C
154   30.0    193.0   6.9     9   26  2010    70      PS
155    NaN    145.0  13.2     9   27  2010    77       S
156   14.0    191.0  14.3     9   28  2010    75       S
157   18.0    131.0   8.0     9   29  2010    76       C

[158 rows x 8 columns]

In [18]:
#Unwanted columns (Unnamed and Temp C) are removed as mentioned.

In [19]:
#check for null values
weather_data.isna().sum()

Ozone      38
Solar.R     7
Wind        0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [20]:
#38 null entries are available on Ozone feature, Since this shows 25% of the data on actual dataset are null, this column is removed

In [21]:
del weather_data["Ozone"]

In [22]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [23]:
weather_data.isna().sum()

Solar.R    7
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [24]:
# Solar.R feature contains 7 null entries and this can be filled with mean data

In [25]:
weather_data.groupby("Weather")["Solar.R"].mean().round()

Weather
C     192.0
PS    174.0
S     193.0
Name: Solar.R, dtype: float64

In [33]:
#transform
weather_data["Solar.R"] = weather_data.groupby("Weather")["Solar.R"].transform(lambda x: x.fillna(x.mean().round()))
weather_data

     Solar.R  Wind Month  Day  Year  Temp Weather
0      190.0   7.4     5    1  2010    67       S
1      118.0   8.0     5    2  2010    72       C
2      149.0  12.6     5    3  2010    74      PS
3      313.0  11.5     5    4  2010    62       S
4      193.0  14.3     5    5  2010    56       S
..       ...   ...   ...  ...   ...   ...     ...
153    190.0   7.4     5    1  2010    67       C
154    193.0   6.9     9   26  2010    70      PS
155    145.0  13.2     9   27  2010    77       S
156    191.0  14.3     9   28  2010    75       S
157    131.0   8.0     9   29  2010    76       C

[158 rows x 7 columns]

In [34]:
weather_data.isna().sum()

Solar.R    3
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [35]:
#important - if the output feature (Weather column) is NaN and Solar.R is also NaN, delete those rows

weather_data.dropna(inplace=True)

In [36]:
weather_data.isna().sum()

Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [37]:
#remove null entries
#fill with mean median mode imputation
#change the data type
#get unique values of Month column

weather_data["Month"]. unique()

array(['5', 'May', '6', '7', '8', '9'], dtype=object)

In [42]:
#change the value of Month feature from 'May' to 5
import warnings
warnings.filterwarnings(action="ignore")
weather_data["Month"].replace(to_replace="May", value=5, inplace=True)

In [44]:
#change the data type of Month column to int

weather_data["Month"] = weather_data["Month"].astype("int")
weather_data.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [45]:
#after data cleaning, input features data type is in numerics and output feature is in object, it has to be addressed

#### 4.2 Data Transformation

In [46]:
#keep a copy before applying transformation as the data is cleaned
weather_data_copy_01 = weather_data.copy()

In [49]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

le_encoder = LabelEncoder()

#fit and transform Weather feature (S = 2, C = 0, PS = 1)
weather_data_copy_01["Weather"] = le_encoder.fit_transform(weather_data_copy_01["Weather"])

In [50]:
weather_data_copy_01

     Solar.R  Wind  Month  Day  Year  Temp  Weather
0      190.0   7.4      5    1  2010    67        2
1      118.0   8.0      5    2  2010    72        0
2      149.0  12.6      5    3  2010    74        1
3      313.0  11.5      5    4  2010    62        2
4      193.0  14.3      5    5  2010    56        2
..       ...   ...    ...  ...   ...   ...      ...
153    190.0   7.4      5    1  2010    67        0
154    193.0   6.9      9   26  2010    70        1
155    145.0  13.2      9   27  2010    77        2
156    191.0  14.3      9   28  2010    75        2
157    131.0   8.0      9   29  2010    76        0

[155 rows x 7 columns]

#### OneHotEncoder usage

    This can be achieved by using any of the two following libraries:
    a. Pandas - pd.get_dummies()
    b. sklearn - OneHotEncoder()

In [51]:
weather_data_copy_02 = weather_data.copy()
weather_data_copy_02

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [54]:
#using pandas get dummies option

In [52]:
weather_data_copy_02 = pd.get_dummies(data=weather_data_copy_02, columns=["Weather"], dtype="int")
weather_data_copy_02

     Solar.R  Wind  Month  Day  Year  Temp  Weather_C  Weather_PS  Weather_S
0      190.0   7.4      5    1  2010    67          0           0          1
1      118.0   8.0      5    2  2010    72          1           0          0
2      149.0  12.6      5    3  2010    74          0           1          0
3      313.0  11.5      5    4  2010    62          0           0          1
4      193.0  14.3      5    5  2010    56          0           0          1
..       ...   ...    ...  ...   ...   ...        ...         ...        ...
153    190.0   7.4      5    1  2010    67          1           0          0
154    193.0   6.9      9   26  2010    70          0           1          0
155    145.0  13.2      9   27  2010    77          0           0          1
156    191.0  14.3      9   28  2010    75          0           0          1
157    131.0   8.0      9   29  2010    76          1           0          0

[155 rows x 9 columns]

In [53]:
weather_data_copy_02.dtypes

Solar.R       float64
Wind          float64
Month           int64
Day             int64
Year            int64
Temp            int64
Weather_C       int64
Weather_PS      int64
Weather_S       int64
dtype: object

In [55]:
# using OneHotEncoder option

In [71]:
weather_data_copy_03 = weather_data.copy()
weather_data_copy_03

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [76]:
ohb = OneHotEncoder()

encoded = ohb.fit_transform(weather_data_copy_03[["Weather"]])
encoded.toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]])