## 1. Import Necessary Libraries

In [14]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, KFold, LeaveOneOut, cross_val_score

## 2. Data Collection

In [2]:
claimants_data = pd.read_csv("claimants_data.csv")
claimants_data

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1335    34100         1     0.0       1.0       0.0     NaN   0.576
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 7 columns]

## 3. Data Understanding

In [3]:
claimants_data.shape

(1340, 7)

In [4]:
claimants_data.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [5]:
claimants_data.dtypes

CASENUM       int64
ATTORNEY      int64
CLMSEX      float64
CLMINSUR    float64
SEATBELT    float64
CLMAGE      float64
LOSS        float64
dtype: object

In [6]:
claimants_data.describe()

,CASENUM,ATTORNEY,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
count,1340.000000,1340.000000,1328.000000,1299.000000,1292.000000,1151.000000,1340.000000
mean,11202.001493,0.488806,0.558735,0.907621,0.017028,28.414422,3.806307
std,9512.750796,0.500061,0.496725,0.289671,0.129425,20.304451,10.636903
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4177.000000,0.000000,0.000000,1.000000,0.000000,9.000000,0.400000
50%,8756.500000,0.000000,1.000000,1.000000,0.000000,30.000000,1.069500
75%,15702.500000,1.000000,1.000000,1.000000,0.000000,43.000000,3.781500
max,34153.000000,1.000000,1.000000,1.000000,1.000000,95.000000,173.604000

## 4. Data Preparation

#### 4.1 Data Cleaning

In [7]:
claimants_data.dropna(inplace=True)
claimants_data
claimants_data.isna().sum()

CASENUM     0
ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

#### 4.2 Separate Input and Output

In [8]:
X = claimants_data.drop(labels=["CASENUM", "ATTORNEY"], axis=1)

In [9]:
X

      CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0        0.0       1.0       0.0    50.0  34.940
1        1.0       0.0       0.0    18.0   0.891
2        0.0       1.0       0.0     5.0   0.330
3        0.0       1.0       1.0    31.0   0.037
4        0.0       1.0       0.0    30.0   0.038
...      ...       ...       ...     ...     ...
1334     1.0       1.0       0.0    16.0   0.060
1336     1.0       1.0       0.0    46.0   3.705
1337     1.0       1.0       0.0    39.0   0.099
1338     1.0       0.0       0.0     8.0   3.177
1339     1.0       1.0       0.0    30.0   0.688

[1096 rows x 5 columns]

In [10]:
y= claimants_data["ATTORNEY"]
y

0       0
1       1
2       1
3       0
4       1
       ..
1334    1
1336    0
1337    1
1338    0
1339    1
Name: ATTORNEY, Length: 1096, dtype: int64

## 5. Model Building

#### Model Validation Techniques

##### 5.1 Train Test Split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, shuffle=True, random_state=42)
X_train

      CLMSEX  CLMINSUR  SEATBELT  CLMAGE   LOSS
2        0.0       1.0       0.0     5.0  0.330
6        0.0       1.0       0.0     9.0  3.538
719      1.0       1.0       0.0    33.0  0.781
769      1.0       1.0       0.0    40.0  0.969
1035     0.0       1.0       0.0    10.0  0.663
...      ...       ...       ...     ...    ...
393      1.0       1.0       0.0     3.0  0.035
572      0.0       1.0       0.0     3.0  0.600
152      1.0       1.0       0.0     6.0  0.075
1275     1.0       1.0       0.0     5.0  0.190
1056     0.0       1.0       0.0    49.0  0.095

[876 rows x 5 columns]

In [13]:
X_test

     CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
51      0.0       1.0       0.0    54.0   0.975
694     0.0       1.0       0.0    19.0   0.348
70      0.0       1.0       0.0    56.0  44.060
774     1.0       1.0       0.0     6.0   0.109
595     0.0       1.0       0.0    31.0   5.550
..      ...       ...       ...     ...     ...
931     1.0       1.0       0.0     6.0   0.036
877     0.0       1.0       0.0    37.0   8.075
443     1.0       1.0       0.0     7.0   0.557
357     1.0       1.0       0.0    31.0   9.017
343     1.0       1.0       0.0    16.0   0.861

[220 rows x 5 columns]

##### 5.2 K-Fold Cross Validation

In [19]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)
kfold.n_splits

5

In [16]:
logistics_model = LogisticRegression()

In [21]:
cv_scores = cross_val_score(estimator=logistics_model, X=X, y=y,cv=kfold)
print(cv_scores)
print("Overall Accuracy:", cv_scores.mean().round(2))
print("Overall Deviation:", cv_scores.std().round(2))

[0.67727273 0.71689498 0.71232877 0.69406393 0.73059361]
Overall Accuracy: 0.71
Overall Deviation: 0.02

#### 5.3 LOOCV - Leave One Out Cross Validation

In [24]:
l_cv = LeaveOneOut()

In [25]:
cv_scores = cross_val_score(estimator=logistics_model, X=X, y=y,cv=l_cv)
print(cv_scores)
print("Overall Accuracy:", cv_scores.mean().round(2))
print("Overall Deviation:", cv_scores.std().round(2))

[1. 1. 1. ... 1. 1. 1.]
Overall Accuracy: 0.7
Overall Deviation: 0.46